package View;

import controller.LoginController;
import controller.PostController;

/**
 *
 * @author amang
 */
public class Doctor_Availability extends javax.swing.JFrame {

    private String doc_email4;
    private String doc_name4;
    private String doc_department1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Doctor_Availability.class.getName());

    /**
     * Creates new form Dashboard_Patient
     */
    public Doctor_Availability() {
        initComponents();
        doc_department.setEditable(false);
        doc_email.setEditable(false);
        doc_name.setEditable(false);

        doc_email4 = LoginController.currentDoctor();
        doc_name4 = LoginController.NameDoctor();
        doc_department1 = LoginController.docDepartment();

        doc_email.setText(doc_email4 != null ? doc_email4 : "");
        doc_name.setText(doc_name4 != null ? doc_name4 : "");
        doc_department.setText(doc_department1 != null ? doc_department1 : "");

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_doc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        doc_name = new javax.swing.JTextField();
        post_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        time_txt1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doc_department = new javax.swing.JTextField();
        date_txt3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        doc_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(795, 565));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(240, 230, 230));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLINIC MANAGEMENT SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(64, 14, 382, 49);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Set Availability");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 90, 180, 40);

        name_doc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        name_doc.setForeground(new java.awt.Color(255, 255, 255));
        name_doc.setText("Name");
        jPanel1.add(name_doc);
        name_doc.setBounds(70, 160, 79, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 460, 80, 20);

        doc_name.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jPanel1.add(doc_name);
        doc_name.setBounds(250, 150, 275, 40);

        post_btn.setBackground(new java.awt.Color(153, 255, 153));
        post_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        post_btn.setText("Post");
        post_btn.addActionListener(this::post_btnActionPerformed);
        jPanel1.add(post_btn);
        post_btn.setBounds(320, 510, 120, 30);

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Go To Dashboard ");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 520, 170, 30);

        time_txt1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jPanel1.add(time_txt1);
        time_txt1.setBounds(250, 450, 275, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 380, 79, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 300, 190, 30);

        doc_department.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jPanel1.add(doc_department);
        doc_department.setBounds(250, 290, 275, 40);

        date_txt3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jPanel1.add(date_txt3);
        date_txt3.setBounds(250, 370, 275, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 220, 79, 30);

        doc_email.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jPanel1.add(doc_email);
        doc_email.setBounds(250, 220, 275, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void post_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_post_btnActionPerformed
        // TODO add your handling code here:

        String date1 = date_txt3.getText().trim();
        String time1 = time_txt1.getText().trim();

        if (date1.isEmpty() || time1.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Date and time are required.");
            return;
        }
        if (!date1.matches("\\d{4}-\\d{2}-\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Use date format yyyy-MM-dd.");
            return;
        }
        if (!time1.matches("\\d{2}:\\d{2}:\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Use time format HH:mm:ss.");
            return;
        }

        PostController postController = new PostController();
        postController.saveDoctorAvailability(doc_name4, doc_email4, date1, time1, doc_department1);
        date_txt3.setText("");
        time_txt1.setText("");

    }// GEN-LAST:event_post_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Doctor_Dashboard dWin = new Doctor_Dashboard();
        dWin.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Doctor_Availability().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date_txt3;
    private javax.swing.JTextField doc_department;
    private javax.swing.JTextField doc_email;
    private javax.swing.JTextField doc_name;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name_doc;
    private javax.swing.JButton post_btn;
    private javax.swing.JTextField time_txt1;
    // End of variables declaration//GEN-END:variables
}
