/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.SignUpController;

/**
 *
 * @author amritchand
 */
public class SignUpUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpUI.class.getName());

    /**
     * Creates new form SignUpUI
     */
    public SignUpUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        confirmPassword = new javax.swing.JTextField();
        btnSignup = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Email");
        jPanel26.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 138, 222, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Phone number");
        jPanel26.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 214, 222, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Name");
        jPanel26.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 139, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel26.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 356, 121, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel26.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 222, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel26.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 164, 300, 44));

        phoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberFocusLost(evt);
            }
        });
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        jPanel26.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 300, 41));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        jPanel26.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 300, 37));

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel26.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 301, 44));

        confirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusLost(evt);
            }
        });
        jPanel26.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 300, 41));

        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignup.setText("Sign up as patient.");
        jPanel26.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 190, 30));

        logIn.setBackground(new java.awt.Color(204, 255, 255));
        logIn.setText("Already have an account.");
        logIn.setBorder(null);
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        jPanel26.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 170, 30));

        jButton1.setText("SignUp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 100, 40));

        jPanel1.add(jPanel26);
        jPanel26.setBounds(440, 0, 560, 700);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clinic Management System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 410, 370, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailActionPerformed

    private void phoneNumberFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_phoneNumberFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_phoneNumberFocusGained

    private void phoneNumberFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_phoneNumberFocusLost
        // TODO add your handling code here:

    }// GEN-LAST:event_phoneNumberFocusLost

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phoneNumberActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_nameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFocusLost

    private void confirmPasswordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_confirmPasswordFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_confirmPasswordFocusGained

    private void confirmPasswordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_confirmPasswordFocusLost
        // TODO add your handling code here:
    }// GEN-LAST:event_confirmPasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email1 = email.getText().trim();
        String phoneNum = phoneNumber.getText().trim();
        String name1 = name.getText().trim();
        String pass1 = password.getText().trim();
        String confirmPass = confirmPassword.getText().trim();

        SignUpController controller = new SignUpController();
        boolean done = controller.registerUser(name1, email1, phoneNum, pass1, confirmPass);
        if (done) {
            LoginUi lWin = new LoginUi();
            lWin.setVisible(true);
            this.dispose();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
        LoginUi lWin = new LoginUi();
        lWin.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_logInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignup;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JButton logIn;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables
}
